---
kind: pipeline
name: pipeline_a

steps:
- name: build
  image: alpine
  commands:
  - sleep 10
  - exit 1

---
kind: pipeline
name: pipeline_b

steps:
- name: build
  image: alpine
  commands:
  - exit 0

---
kind: pipeline
name: notify

steps:
- name: notify
  image: alpine
  commands:
  - exit 0

depends_on:
- pipeline_a
- pipeline_b

trigger:
  status:
  - failure
...
